# Generated by Django 4.0.4 on 2022-04-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMatafuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Categoria Matafuegos',
            },
        ),
    ]
