# Generated by Django 4.0.4 on 2022-04-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_codigo_alter_cliente_cuit_cuil_and_more'),
        ('orden_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
            preserve_default=False,
        ),
    ]
