# Generated by Django 4.0.4 on 2022-04-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_codigo_alter_cliente_cuit_cuil_and_more'),
        ('orden_trabajo', '0002_ordenes_de_trabajo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
