# Generated by Django 4.0.4 on 2022-04-26 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0003_alter_ordenes_de_trabajo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes_de_trabajo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='estado',
            field=models.CharField(choices=[('p', 'Pendiente'), ('ep', 'En proceso'), ('f', 'Finalizada'), ('c', 'cancelada')], default='a', max_length=80, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de realización'),
        ),
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='fecha_cierre',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='fecha_entrega',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de entrega estimada'),
        ),
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='notas',
            field=models.CharField(default=' ', max_length=80, verbose_name='notas'),
        ),
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Numero'),
        ),
    ]
