# Generated by Django 4.0.4 on 2022-04-26 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0004_remove_ordenes_de_trabajo_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='estado',
            field=models.CharField(choices=[('p', 'Pendiente'), ('ep', 'En proceso'), ('f', 'Finalizada'), ('c', 'cancelada')], default='p', max_length=80, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='fecha_cierre',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Fecha de cierre'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='notas',
            field=models.CharField(blank=True, max_length=80, verbose_name='notas'),
        ),
    ]
