# Generated by Django 4.0.4 on 2022-04-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0005_tarea_precio_alter_ordenes_de_trabajo_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea_Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.ordenes_de_trabajo')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.tarea')),
            ],
        ),
    ]
