# Generated by Django 4.0.4 on 2022-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0006_tarea_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='monto_total',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
