# Generated by Django 4.0.4 on 2022-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0008_alter_ordenes_de_trabajo_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='monto_total',
            field=models.FloatField(default=0, verbose_name='monto'),
        ),
    ]
