# Generated by Django 4.0.4 on 2022-04-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0009_alter_ordenes_de_trabajo_monto_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenes_de_trabajo',
            options={'verbose_name_plural': 'Ordenes de trabajo'},
        ),
        migrations.AlterModelOptions(
            name='tarea_orden',
            options={'verbose_name_plural': 'Tarea - Orden de trabajo'},
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='monto_total',
            field=models.FloatField(default=0, editable=False, verbose_name='monto'),
        ),
    ]
