# Generated by Django 4.0.4 on 2022-04-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0001_initial'),
        ('orden_trabajo', '0010_alter_ordenes_de_trabajo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='matafuego',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matafuegos.matafuegos'),
            preserve_default=False,
        ),
    ]
