# Generated by Django 4.0.4 on 2022-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0011_ordenes_de_trabajo_matafuego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
    ]
