# Generated by Django 4.0.4 on 2022-04-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0013_rename_matafuego_ordenes_de_trabajo_matafuegos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenes_de_trabajo',
            old_name='matafuegos',
            new_name='matafuego',
        ),
    ]
