# Generated by Django 4.0.4 on 2022-04-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0014_rename_matafuegos_ordenes_de_trabajo_matafuego'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenes_de_trabajo',
            old_name='matafuego',
            new_name='matafuegos',
        ),
    ]
