# Generated by Django 4.0.4 on 2022-05-04 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0015_rename_matafuego_ordenes_de_trabajo_matafuegos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarea_Orden',
            new_name='TareaOrden',
        ),
        migrations.RemoveField(
            model_name='ordenes_de_trabajo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ordenes_de_trabajo',
            name='numero',
        ),
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de creacioin de orden'),
        ),
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='monto_total',
            field=models.FloatField(default=0, verbose_name='Monto'),
        ),
    ]
