# Generated by Django 4.0.4 on 2022-05-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0016_rename_tarea_orden_tareaorden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaorden',
            name='precio',
            field=models.FloatField(null=True, verbose_name='precio ajustable'),
        ),
    ]
