# Generated by Django 4.0.4 on 2022-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0017_tareaorden_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareaorden',
            name='precio',
        ),
        migrations.AddField(
            model_name='tareaorden',
            name='precioAj',
            field=models.FloatField(blank=True, default=0, verbose_name='precio ajustable'),
        ),
    ]
