# Generated by Django 4.0.4 on 2022-05-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0018_remove_tareaorden_precio_tareaorden_precioaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaorden',
            name='precioAj',
            field=models.FloatField(default=0, verbose_name='precio ajustable'),
        ),
    ]
