# Generated by Django 4.0.4 on 2022-05-10 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0022_alter_tareaorden_precioaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='estado',
            field=models.CharField(blank=True, choices=[('p', 'Pendiente'), ('ep', 'En proceso'), ('f', 'Finalizada'), ('c', 'cancelada')], default='p', max_length=80, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_trabajo',
            name='fecha_entrega',
            field=models.DateField(default=datetime.date.today, verbose_name='Entrega estimada'),
        ),
    ]
