# Generated by Django 4.0.4 on 2022-05-11 13:17

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0025_alter_ordenes_de_trabajo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('publications', models.ManyToManyField(blank=True, null=True, to='orden_trabajo.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.publication')),
                ('writer', smart_selects.db_fields.ChainedManyToManyField(chained_field='publication', chained_model_field='publications', horizontal=True, to='orden_trabajo.writer', verbose_name='writer')),
            ],
        ),
    ]
