# Generated by Django 4.0.4 on 2022-05-11 13:28

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0006_alter_matafuegos_cliente'),
        ('orden_trabajo', '0026_publication_writer_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='ordenes_de_trabajo',
            name='matafuegos',
        ),
        migrations.AddField(
            model_name='ordenes_de_trabajo',
            name='matafuego',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='cliente', chained_model_field='cliente', horizontal=True, to='matafuegos.matafuegos', verbose_name='matafuego'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
