# Generated by Django 4.0.4 on 2022-04-27 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0007_alter_cliente_codigo_alter_cliente_cuit_cuil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMatafuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Categoria Matafuegos',
            },
        ),
        migrations.CreateModel(
            name='MarcaMatafuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Marca Matafuegos',
            },
        ),
        migrations.CreateModel(
            name='TipoMatafuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('vencimiento_carga', models.IntegerField(verbose_name='Vencimiento de carga')),
                ('vencimiento_ph', models.IntegerField(verbose_name='Vencimiento de PH')),
                ('volumen', models.FloatField(verbose_name='Volumen')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matafuegos.categoriamatafuegos')),
            ],
            options={
                'verbose_name_plural': 'Tipo Matafuegos',
            },
        ),
        migrations.CreateModel(
            name='Matafuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('numero_bv', models.IntegerField(verbose_name='Numero de BV')),
                ('numero_dps', models.IntegerField(verbose_name='Numero de DPS')),
                ('patente', models.CharField(blank=True, max_length=20, verbose_name='Patente')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('localización', models.CharField(blank=True, max_length=100, verbose_name='Localizacion')),
                ('numero_localizacion', models.IntegerField(blank=True, null=True, verbose_name='Numero de localizacion')),
                ('categoria', models.CharField(choices=[('v', 'Vehicular'), ('d', 'Domiciliario')], max_length=100, verbose_name='Categoria')),
                ('centro_costo', models.CharField(max_length=100, verbose_name='Centro de costo')),
                ('fecha_fabricación', models.DateField()),
                ('fecha_carga', models.DateField(default=datetime.date.today)),
                ('fecha_proxima_carga', models.DateField(blank=True, null=True)),
                ('fecha_ph', models.DateField(default=datetime.date.today)),
                ('fecha_proxima_ph', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matafuegos.marcamatafuegos')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matafuegos.tipomatafuegos')),
            ],
            options={
                'verbose_name_plural': 'Matafuegos',
            },
        ),
    ]
