# Generated by Django 4.0.4 on 2022-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMatafuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Categoria Matafuegos',
            },
        ),
        migrations.CreateModel(
            name='MarcaMatafuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Marca Matafuegos',
            },
        ),
        migrations.CreateModel(
            name='Matafuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('numero_bv', models.IntegerField(verbose_name='Numero de BV')),
                ('numero_dps', models.IntegerField(verbose_name='Numero de DPS')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('localización', models.CharField(max_length=100, verbose_name='Localizacion')),
                ('numero_localizacion', models.IntegerField(verbose_name='Numero de localizacion')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('centro_costo', models.CharField(max_length=100, verbose_name='Centro de costo')),
                ('fecha_fabricación', models.DateTimeField()),
                ('fecha_carga', models.DateTimeField()),
                ('fecha_proxima_carga', models.DateTimeField()),
                ('fecha_ph', models.DateTimeField()),
                ('fecha_proxima_ph', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Matafuegos',
            },
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_inicio', models.IntegerField(verbose_name='VEH Inicio')),
                ('veh_fin', models.IntegerField(verbose_name='VEH Fin')),
                ('veh_prefijo', models.IntegerField(verbose_name='VEH Prefijo')),
                ('veh_actual', models.IntegerField(verbose_name='VEH Actual')),
                ('dom_inicio', models.IntegerField(verbose_name='DOM Inicio')),
                ('dom_fin', models.IntegerField(verbose_name='DOM Fin')),
                ('dom_prefijo', models.IntegerField(verbose_name='DOM Prefijo')),
                ('dom_actual', models.IntegerField(verbose_name='DOM Actual')),
            ],
            options={
                'verbose_name_plural': 'Parametros',
            },
        ),
        migrations.CreateModel(
            name='TipoMatafuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('vencimiento_carga', models.IntegerField(verbose_name='Vencimiento de carga')),
                ('vencimiento_ph', models.IntegerField(verbose_name='Vencimiento de PH')),
                ('volumen', models.IntegerField(verbose_name='Volumen')),
                ('peso', models.IntegerField(verbose_name='Peso')),
            ],
            options={
                'verbose_name_plural': 'Tipo Matafuegos',
            },
        ),
    ]
