# Generated by Django 4.0.4 on 2022-04-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matafuegos.marcamatafuegos'),
        ),
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matafuegos.categoriamatafuegos'),
        ),
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='peso',
            field=models.FloatField(verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='tipomatafuegos',
            name='volumen',
            field=models.FloatField(verbose_name='Volumen'),
        ),
    ]
