# Generated by Django 4.0.4 on 2022-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0002_alter_matafuegos_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='localización',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localizacion'),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='numero_localizacion',
            field=models.IntegerField(blank=True, verbose_name='Numero de localizacion'),
        ),
    ]
