# Generated by Django 4.0.4 on 2022-04-25 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_codigo_alter_cliente_cuit_cuil_and_more'),
        ('matafuegos', '0003_alter_matafuegos_localización_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matafuegos',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matafuegos',
            name='patente',
            field=models.CharField(blank=True, max_length=20, verbose_name='Patente'),
        ),
        migrations.AddField(
            model_name='matafuegos',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matafuegos.tipomatafuegos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_carga',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_fabricación',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_ph',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_proxima_carga',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_proxima_ph',
            field=models.DateField(),
        ),
    ]
