# Generated by Django 4.0.4 on 2022-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0004_matafuegos_cliente_matafuegos_patente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='numero_localizacion',
            field=models.IntegerField(null=True, verbose_name='Numero de localizacion'),
        ),
    ]
