# Generated by Django 4.0.4 on 2022-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0006_matafuegos_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='categoria',
            field=models.CharField(choices=[('v', 'Vehicular'), ('d', 'Domiciliario')], max_length=100, verbose_name='Categoria'),
        ),
    ]
