# Generated by Django 4.0.4 on 2022-04-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0007_alter_matafuegos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_fabricación',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_proxima_carga',
            field=models.DateField(editable=False),
        ),
    ]
