# Generated by Django 4.0.4 on 2022-04-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0010_alter_matafuegos_fecha_proxima_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_proxima_carga',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_proxima_ph',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
