# Generated by Django 4.0.4 on 2022-04-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0011_alter_matafuegos_fecha_proxima_carga_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametros',
        ),
    ]
