# Generated by Django 4.0.4 on 2022-04-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matafuegos', '0012_delete_parametros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_proxima_carga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matafuegos',
            name='fecha_proxima_ph',
            field=models.DateField(blank=True, null=True),
        ),
    ]
