# Generated by Django 4.0.4 on 2022-04-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_inicio', models.IntegerField(verbose_name='VEH Inicio')),
                ('veh_fin', models.IntegerField(verbose_name='VEH Fin')),
                ('veh_prefijo', models.IntegerField(verbose_name='VEH Prefijo')),
                ('veh_actual', models.IntegerField(verbose_name='VEH Actual')),
                ('dom_inicio', models.IntegerField(verbose_name='DOM Inicio')),
                ('dom_fin', models.IntegerField(verbose_name='DOM Fin')),
                ('dom_prefijo', models.IntegerField(verbose_name='DOM Prefijo')),
                ('dom_actual', models.IntegerField(verbose_name='DOM Actual')),
            ],
            options={
                'verbose_name_plural': 'Parametros',
            },
        ),
    ]
