# Generated by Django 4.0.4 on 2022-05-31 13:57

from django.db import migrations
from django.core.management import call_command

fixture = 'export_interface'

def crear_registros_interface(apps, schema_editor):
    call_command('loaddata', fixture, app_label='parametros')

class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_auto_20220531_1344'),
    ]

    operations = [
        migrations.RunPython(crear_registros_interface)
    ]
