# Generated by Django 4.0.4 on 2022-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit_cuil', models.IntegerField(verbose_name='CUIT/CUIL')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre/ Razón Social')),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('email', models.EmailField(max_length=264, verbose_name='Email')),
                ('web', models.CharField(max_length=200, verbose_name='Web')),
                ('tipo', models.CharField(choices=[('p', 'persona'), ('e', 'empresa')], default='p', max_length=80, verbose_name='tipo')),
            ],
        ),
    ]
