# Generated by Django 4.0.4 on 2022-04-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit_cuil',
            field=models.IntegerField(verbose_name='CUIT/CUIL*'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=80, verbose_name='Dirección*'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=264, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre/ Razón Social*'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=100, verbose_name='Telefono*'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('p', 'Persona'), ('e', 'Empresa')], default='p', max_length=80, verbose_name='tipo*'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='web',
            field=models.CharField(blank=True, max_length=200, verbose_name='Web'),
        ),
    ]
