# Generated by Django 4.0.4 on 2022-04-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_cuit_cuil_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Matafuegos'},
        ),
    ]
