# Generated by Django 4.0.4 on 2022-04-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.IntegerField(default=233, verbose_name='Codigo*'),
            preserve_default=False,
        ),
    ]
