# Generated by Django 4.0.4 on 2022-04-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_cliente_estado_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.IntegerField(verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuit_cuil',
            field=models.IntegerField(verbose_name='CUIT/CUIL'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=80, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=80, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre/ Razón Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=100, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('p', 'Persona'), ('e', 'Empresa')], default='p', max_length=80, verbose_name='Tipo'),
        ),
    ]
